name: Notify Orchestrator (DEV & PROMOTE)

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Determine event type
        id: kind
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "type=deploy_dev" >> $GITHUB_OUTPUT
          else
            echo "type=promote" >> $GITHUB_OUTPUT
          fi

      - name: Call Orchestrator via repository_dispatch
        env:
          # Fine-grained PAT with "Contents: Read" on app repos and "Actions: Read/Write" on the orchestration repo
          ORCHESTRATOR_PAT: ${{ secrets.ORCHESTRATOR_PAT }}
          ORG: $${{ vars.orgname}}                        # <-- change
          ORCHESTRATOR_REPO: $${{vars.orchestrator-repo}}    # <-- change (central repo name)
        run: |
          payload=$(jq -n \
            --arg repo_full_name "${GITHUB_REPOSITORY}" \
            --arg repo "${GITHUB_REPOSITORY##*/}" \
            --arg sha "${GITHUB_SHA}" \
            --arg ref "${GITHUB_REF_NAME}" \
            --arg sender "${{ github.actor }}" \
            '{
              "repo_full_name": $repo_full_name,
              "repo": $repo,
              "sha": $sha,
              "ref": $ref,
              "sender": $sender
            }')
          curl -s -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${ORCHESTRATOR_PAT}" \
            https://api.github.com/repos/${ORG}/${ORCHESTRATOR_REPO}/dispatches \
            -d "$(jq -n --arg type "${{ steps.kind.outputs.type }}" --argjson client_payload "${payload}" '{event_type: $type, client_payload: $client_payload}')"
